version: 2
jobs:
  build_and_test_back:
    docker:
      - image: circleci/python:3.6
      - image: mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
    working_directory: ~/jyll
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "backend/requirements.txt" }}
      - run:
          name: Installing python dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r backend/requirements.txt
      - save_cache:
          key: dependencies-{{ checksum "backend/requirements.txt" }}
          paths:
            - venv
      - run:
          name: Installing RabbitMQ
          command: |
            sudo apt-get install rabbitmq-server
      - run:
          name: Installing mariadb client
          command: |
            sudo apt-get update && sudo apt-get install -y mariadb-client
      - run:
          name: Waiting for mysql server
          command: |
            wget https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz && \
            sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-v0.6.1.tar.gz && \
            rm dockerize-linux-amd64-v0.6.1.tar.gz && \
            dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: Creating mariadb user
          command: |
            echo "CREATE USER 'jyll'@'127.0.0.1' IDENTIFIED BY 'password';
                  GRANT ALL PRIVILEGES ON jyll.* TO 'jyll'@'127.0.0.1';
                  GRANT ALL PRIVILEGES ON test_jyll.* TO 'jyll'@'127.0.0.1';
                  FLUSH PRIVILEGES;" | mysql -h 127.0.0.1 -u root
      - run:
          name: Running backend tests
          command: |
            sudo service rabbitmq-server start
            . venv/bin/activate
            cd backend && python manage.py test

workflows:
  version: 2
  build_and_test_back:
    jobs:
      - build_and_test_back
