# Generated by Django 3.0.2 on 2020-02-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_game_and_player_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
