# Generated by Django 3.0.2 on 2020-03-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_make_game_password_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
