# Generated by Django 3.0.2 on 2020-06-21 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_add_player_field_is_ready"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resources",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("money", models.FloatField(default=0)),
                ("hydrocarbon", models.FloatField(default=0)),
                (
                    "player",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="game.Player"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerRatings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("economy", models.FloatField(default=0)),
                ("society", models.FloatField(default=0)),
                ("environment", models.FloatField(default=0)),
                (
                    "player",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="game.Player"
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="PlayerProduction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("money", models.FloatField(default=0)),
                ("hydrocarbon", models.FloatField(default=0)),
                ("hydrocarbon_consumption", models.FloatField(default=0)),
                ("food", models.FloatField(default=0)),
                ("electricity", models.FloatField(default=0)),
                ("waste", models.FloatField(default=0)),
                ("pollution", models.FloatField(default=0)),
                ("science", models.FloatField(default=0)),
                (
                    "player",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="game.Player"
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="HydrocarbonSupply",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drawn_amount", models.FloatField(default=0)),
                (
                    "game",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="game.Game"
                    ),
                ),
            ],
        ),
    ]
