# Generated by Django 3.0.2 on 2020-06-29 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_add_ressources_production_ratings_hydrocarbon_supply"),
    ]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_idx", models.IntegerField()),
                ("copies", models.IntegerField(default=0)),
                ("quantity_cap", models.IntegerField(default=0)),
                ("cost", models.FloatField(default=0)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="building",
                        to="game.Player",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="hydrocarbonsupply",
            name="game",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hydrocarbon_supply",
                to="game.Game",
            ),
        ),
        migrations.AlterField(
            model_name="playerproduction",
            name="player",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="production",
                to="game.Player",
            ),
        ),
        migrations.AlterField(
            model_name="playerratings",
            name="player",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="game.Player",
            ),
        ),
        migrations.CreateModel(
            name="Factory",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="game.Building",
                    ),
                ),
            ],
            bases=("game.building",),
        ),
        migrations.CreateModel(
            name="Lab",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="game.Building",
                    ),
                ),
            ],
            bases=("game.building",),
        ),
        migrations.CreateModel(
            name="BuildingRatings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("economy", models.FloatField(default=0)),
                ("society", models.FloatField(default=0)),
                ("environment", models.FloatField(default=0)),
                (
                    "building",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="game.Building"
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="BuildingProduction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("money", models.FloatField(default=0)),
                ("hydrocarbon", models.FloatField(default=0)),
                ("hydrocarbon_consumption", models.FloatField(default=0)),
                ("food", models.FloatField(default=0)),
                ("electricity", models.FloatField(default=0)),
                ("waste", models.FloatField(default=0)),
                ("pollution", models.FloatField(default=0)),
                ("science", models.FloatField(default=0)),
                (
                    "building",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="game.Building"
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.AddConstraint(
            model_name="building",
            constraint=models.UniqueConstraint(
                fields=("player", "class_idx"), name="building_unique"
            ),
        ),
    ]
