# Generated by Django 3.0.2 on 2020-07-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0008_refactor_technology"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building", name="cost", field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="building", name="quantity_cap", field=models.IntegerField(),
        ),
    ]
