# Generated by Django 3.0.2 on 2020-07-11 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0009_auto_20200704_1656"),
    ]

    operations = [
        migrations.AddField(
            model_name="lab",
            name="domain_focus",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="science_buildings",
                to="game.TechnologyDomain",
            ),
        ),
    ]
