# Generated by Django 3.0.2 on 2020-07-19 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0011_auto_20200716_1621"),
    ]

    operations = [
        migrations.CreateModel(
            name="TechnologyCost",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField()),
                ("cost", models.FloatField()),
                (
                    "technology",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="level_costs",
                        to="game.Technology",
                    ),
                ),
            ],
        ),
    ]
