# Generated by Django 3.0.2 on 2020-07-20 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0012_technology_cost_model"),
    ]

    operations = [
        migrations.RemoveField(model_name="lab", name="domain_focus",),
        migrations.CreateModel(
            name="ScienceBuildingCopy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="individual_copies",
                        to="game.Building",
                    ),
                ),
                (
                    "domain_focus",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="science_buildings",
                        to="game.TechnologyDomain",
                    ),
                ),
            ],
        ),
    ]
