# Generated by Django 3.0.2 on 2020-11-10 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_auto_20200726_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='player',
            field=models.ForeignKey(db_constraint=False, db_index=False, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='buildings', to='game.Player'),
        ),
        migrations.AlterField(
            model_name='technologydomain',
            name='player',
            field=models.ForeignKey(db_constraint=False, db_index=False, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='domains', to='game.Player'),
        ),
        migrations.RemoveConstraint(
            model_name='building',
            name='building_unique',
        ),
        migrations.RemoveConstraint(
            model_name='technologydomain',
            name='domain_unique',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='class_idx',
            new_name='class_index',
        ),
        migrations.RenameField(
            model_name='technology',
            old_name='class_idx',
            new_name='class_index',
        ),
        migrations.RenameField(
            model_name='technologydomain',
            old_name='domain_idx',
            new_name='domain_index',
        ),
        migrations.RenameField(
            model_name='technologydomain',
            old_name='next_technology_class_idx',
            new_name='next_technology_class_index',
        ),
        migrations.AddConstraint(
            model_name='building',
            constraint=models.UniqueConstraint(fields=('player', 'class_index'), name='building_unique'),
        ),
        migrations.AddConstraint(
            model_name='technologydomain',
            constraint=models.UniqueConstraint(fields=('player', 'domain_index'), name='domain_unique'),
        ),
        migrations.AlterField(
            model_name='building',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings',
                                    to='game.Player'),
        ),
        migrations.AlterField(
            model_name='technologydomain',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains',
                                    to='game.Player'),
        ),
    ]
