# Generated by Django 3.0.2 on 2020-01-10 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_add_user_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
